# Generated by Django 5.0.4 on 2026-04-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('pro', 'Pro'), ('admin', 'Admin')], max_length=20),
        ),
    ]
