# Generated by Django 5.0.4 on 2026-05-26 20:39

import apps.become_pro.models
import apps.become_pro.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_auth_provider_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_required', 'Resubmission Required')], default='draft', max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True)),
                ('service_category', models.CharField(blank=True, choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('chef', 'Chef'), ('labour', 'General Labour'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('cleaner', 'Cleaner'), ('mechanic', 'Mechanic'), ('gardener', 'Gardener'), ('mason', 'Mason')], max_length=50)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('portfolio_link', models.URLField(blank=True)),
                ('kyc_documennt_type', models.CharField(blank=True, choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License')], max_length=20)),
                ('kyc_document_number', models.CharField(blank=True, max_length=50)),
                ('kyc_documennt_front', models.ImageField(blank=True, null=True, upload_to=apps.become_pro.models.ProApplication.application_document_upload_path, validators=[apps.become_pro.validators.validate_file_size])),
                ('kyc_document_back', models.ImageField(blank=True, null=True, upload_to=apps.become_pro.models.ProApplication.application_document_upload_path, validators=[apps.become_pro.validators.validate_file_size])),
                ('selfie_with_id', models.ImageField(blank=True, null=True, upload_to=apps.become_pro.models.ProApplication.application_document_upload_path, validators=[apps.become_pro.validators.validate_file_size])),
                ('kyc_verified', models.BooleanField(default=False)),
                ('pcc_document', models.ImageField(blank=True, null=True, upload_to=apps.become_pro.models.ProApplication.application_document_upload_path, validators=[apps.become_pro.validators.validate_file_size])),
                ('pcc_issue_date', models.DateField(blank=True, null=True)),
                ('pcc_issuing_authority', models.CharField(blank=True, max_length=150)),
                ('pcc_verified', models.BooleanField(default=False)),
                ('skill_certificate_1', models.ImageField(blank=True, null=True, upload_to=apps.become_pro.models.ProApplication.application_document_upload_path, validators=[apps.become_pro.validators.validate_file_size])),
                ('skill_certificate_2', models.ImageField(blank=True, null=True, upload_to=apps.become_pro.models.ProApplication.application_document_upload_path, validators=[apps.become_pro.validators.validate_file_size])),
                ('skill_certificate_3', models.ImageField(blank=True, null=True, upload_to=apps.become_pro.models.ProApplication.application_document_upload_path, validators=[apps.become_pro.validators.validate_file_size])),
                ('skills_verified', models.BooleanField(default=False)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('location_document_type', models.CharField(blank=True, choices=[('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('rent_agreement', 'Rent Agreement'), ('aadhar', 'Aadhar Card (with address)'), ('passport', 'Passport (with address)')], max_length=20)),
                ('location_document', models.ImageField(blank=True, null=True, upload_to=apps.become_pro.models.ProApplication.application_document_upload_path, validators=[apps.become_pro.validators.validate_file_size])),
                ('location_verified', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='users.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_application', to='users.user')),
            ],
            options={
                'verbose_name': 'Pro Application',
                'verbose_name_plural': 'Pro Applications',
                'db_table': 'pro_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
