# Generated by Django 5.0.4 on 2026-05-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('become_pro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proapplication',
            old_name='kyc_documennt_front',
            new_name='kyc_document_front',
        ),
        migrations.RenameField(
            model_name='proapplication',
            old_name='kyc_documennt_type',
            new_name='kyc_document_type',
        ),
    ]
