# Generated by Django 5.0.4 on 2026-05-26 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_auth_provider_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('chef', 'Chef'), ('labour', 'General Labour'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('cleaner', 'Cleaner'), ('mechanic', 'Mechanic'), ('gardener', 'Gardener'), ('mason', 'Mason')], max_length=50)),
                ('experience', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('bio', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cover_photo_url', models.TextField(blank=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_jobs', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_profile', to='users.user')),
            ],
            options={
                'db_table': 'pro_profiles',
            },
        ),
    ]
